# Generated by Django 5.2.6 on 2025-09-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('entreprise', models.CharField(blank=True, max_length=100, verbose_name='Entreprise')),
                ('secteur', models.CharField(blank=True, choices=[('btp', 'BTP'), ('transport', 'Transport'), ('immobilier', 'Immobilier'), ('communication', 'Communication'), ('services', 'Services'), ('security', 'Security'), ('import_export', 'Import/Export')], max_length=50, verbose_name="Secteur d'intérêt")),
                ('sujet', models.CharField(blank=True, max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('ferme', 'Fermé')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes administrateur')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('secteurs_interesse', models.JSONField(blank=True, default=list, verbose_name="Secteurs d'intérêt")),
            ],
            options={
                'verbose_name': 'Abonnement newsletter',
                'verbose_name_plural': 'Abonnements newsletter',
                'ordering': ['-created_at'],
            },
        ),
    ]
