# Generated by Django 5.2.6 on 2025-09-12 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(choices=[('btp', 'BTP'), ('transport', 'Transport'), ('immobilier', 'Immobilier'), ('communication', 'Communication'), ('services', 'Services'), ('security', 'Security'), ('import_export', 'Import/Export')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100, verbose_name="Nom d'affichage")),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.CharField(max_length=200, verbose_name='Description courte')),
                ('icon', models.CharField(default='🏢', max_length=10, verbose_name='Icône')),
                ('image', models.ImageField(blank=True, upload_to='sectors/', verbose_name='Image')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Titre SEO')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Description SEO')),
            ],
            options={
                'verbose_name': 'Secteur',
                'verbose_name_plural': 'Secteurs',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('description', models.TextField(verbose_name='Description')),
                ('client', models.CharField(blank=True, max_length=100, verbose_name='Client')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localisation')),
                ('completion_date', models.DateField(verbose_name='Date de réalisation')),
                ('image', models.ImageField(blank=True, upload_to='projects/', verbose_name='Image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Projet vedette')),
                ('budget_range', models.CharField(blank=True, max_length=50, verbose_name='Fourchette budget')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Durée')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='SectorStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('value', models.CharField(max_length=20, verbose_name='Valeur')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'Statistique secteur',
                'verbose_name_plural': 'Statistiques secteurs',
                'ordering': ['sector', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Icône')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['sector', 'order', 'name'],
            },
        ),
    ]
