# Generated by Django 5.2.6 on 2025-10-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_administrative',
            field=models.BooleanField(default=False, verbose_name='Service administratif'),
        ),
    ]
