# Generated by Django 4.2.7 on 2025-10-27 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0003_remove_sector_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('years_experience', models.PositiveIntegerField(default=10, verbose_name="Années d'expérience")),
                ('completed_projects', models.PositiveIntegerField(default=100, verbose_name='Projets réalisés')),
                ('happy_clients', models.PositiveIntegerField(default=50, verbose_name='Clients satisfaits')),
                ('team_members', models.PositiveIntegerField(default=20, verbose_name="Membres d'équipe")),
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'Statistique de secteur',
                'verbose_name_plural': 'Statistiques de secteur',
            },
        ),
    ]
