# Generated by Django 4.2.7 on 2025-10-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_service_is_administrative'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectorStatistic',
        ),
    ]
